### ISSUE TITLE
Unknown option: direct.presets

### ISSUE THREAD

**Issue by ZebraFlesh** [babel/broccoli-babel-transpiler#106]
I'm attempting to use it like so:

```
const babel = require('broccoli-babel-transpiler');
const apps = babel('src', {
    presets: [ 'react', 'es2015' ]
});
```

And am seeing the following error:
```
ReferenceError: [BABEL] Foo.js: Unknown option: direct.presets
    at Logger.error (C:\inetpub\wwwroot\MyProject\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\file\logger.js:58:11)
    at OptionManager.mergeOptions (C:\inetpub\wwwroot\MyProject\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\file\options\option-manager.js:126:29)
    at OptionManager.init (C:\inetpub\wwwroot\MyProject\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\file\options\option-manager.js:216:10)
    at File.initOptions (C:\inetpub\wwwroot\MyProject\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (C:\inetpub\wwwroot\MyProject\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (C:\inetpub\wwwroot\MyProject\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at Babel.transform (C:\inetpub\wwwroot\MyProject\node_modules\broccoli-babel-transpiler\index.js:105:21)
    at Babel.processString (C:\inetpub\wwwroot\MyProject\node_modules\broccoli-babel-transpiler\index.js:204:25)
    at Promise.then.result.output (C:\inetpub\wwwroot\MyProject\node_modules\broccoli-persistent-filter\lib\strategies\persistent.js:41:23)
    at initializePromise (C:\inetpub\wwwroot\MyProject\node_modules\rsvp\dist\rsvp.js:588:5)
```

Ideally, I'd like to reuse my .babelrc file which happens to contain presets information, but this plugin fails on that as well (with a similar error, Unknown option: .babelrc.presets). So this seems like a reasonable step in that direction.

**Comment by ZebraFlesh** [comment]
My bad, this appears to be an issue with babel 5.x. Updating broccoli-babel-transpiler 6.0.0-alpha.2 resolves this issue.
