### ISSUE TITLE
Is Node 0.12 still supported in v5.x?

### ISSUE THREAD

**Issue by leizhao4** [babel/broccoli-babel-transpiler#111]
If yes, then `broccoli-persistent-filter` -> `async-disk-cache ^1.2.1` -> `username ^2.3.0` breaks Node 0.12 compatibility.

See:
https://github.com/sindresorhus/username/issues/7
https://github.com/stefanpenner/async-disk-cache/pull/43

```
  1) build plugin build hook builds the app and resolves with distDir and distFiles:
     /home/travis/build/ember-cli-deploy/ember-cli-deploy-build/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/async-disk-cache/node_modules/username/index.js:2
const os = require('os');
^^^^^
Use of const in strict mode.
  /home/travis/build/ember-cli-deploy/ember-cli-deploy-build/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/async-disk-cache/node_modules/username/index.js:2
  const os = require('os');
  ^^^^^
  SyntaxError: Use of const in strict mode.
      at exports.runInThisContext (vm.js:73:16)
      at Object.<anonymous> (node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/node_modules/async-disk-cache/index.js:24:16)
```

**Comment by rwjblue** [comment]
This was resolved in async-disk-cache.  Closing.
