### ISSUE TITLE
Parallelization Does Not Interop Between Babel 6 and 7

### ISSUE THREAD

**Issue by chadhietala** [babel/broccoli-babel-transpiler#156]
If you are trying to parallelize and you have some plugin instances that are running 6 and some that are 7, you will error out with an error that looks like this. 

```
ERROR Summary:

  - broccoliBuilderErrorStack: ReferenceError: Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
    at throwUnknownError (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/@babel/core/lib/config/validation/options.js:123:11)
    at Object.keys.forEach.key (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/@babel/core/lib/config/validation/options.js:107:5)
    at Array.forEach (<anonymous>)
    at validateNested (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/@babel/core/lib/config/validation/options.js:83:21)
    at validate (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/@babel/core/lib/config/validation/options.js:74:10)
    at loadPrivatePartialConfig (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/@babel/core/lib/config/partial.js:66:50)
    at loadFullConfig (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/@babel/core/lib/config/full.js:43:39)
    at transformSync (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/@babel/core/lib/transform.js:41:38)
    at Object.transform (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/@babel/core/lib/transform.js:22:38)
    at resolve (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/lib/worker.js:11:29)
  - codeFrame: Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
  - errorMessage: @linkedin/ember-cli-pemberly-lix/client.js: Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
        in /var/folders/qs/ztg_n78d1xvgc2cjcs0gx4ww0008c7/T/broccoli-63768zsIEp42L8w10/out-102-broccoli_persistent_filter_babel_babel_linkedin_ember_c
        at broccoli-persistent-filter:Babel
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: @linkedin/ember-cli-pemberly-lix/client.js
    - line: [undefined]
    - treeDir: /var/folders/qs/ztg_n78d1xvgc2cjcs0gx4ww0008c7/T/broccoli-63768zsIEp42L8w10/out-102-broccoli_persistent_filter_babel_babel_linkedin_ember_c
  - message: @linkedin/ember-cli-pemberly-lix/client.js: Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
        in /var/folders/qs/ztg_n78d1xvgc2cjcs0gx4ww0008c7/T/broccoli-63768zsIEp42L8w10/out-102-broccoli_persistent_filter_babel_babel_linkedin_ember_c
        at broccoli-persistent-filter:Babel
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: broccoli-persistent-filter:Babel
  - originalErrorMessage: Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
  - stack: ReferenceError: Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
    at throwUnknownError (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/@babel/core/lib/config/validation/options.js:123:11)
    at Object.keys.forEach.key (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/@babel/core/lib/config/validation/options.js:107:5)
    at Array.forEach (<anonymous>)
    at validateNested (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/@babel/core/lib/config/validation/options.js:83:21)
    at validate (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/@babel/core/lib/config/validation/options.js:74:10)
    at loadPrivatePartialConfig (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/@babel/core/lib/config/partial.js:66:50)
    at loadFullConfig (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/@babel/core/lib/config/full.js:43:39)
    at transformSync (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/@babel/core/lib/transform.js:41:38)
    at Object.transform (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/@babel/core/lib/transform.js:22:38)
    at resolve (/Users/chietala/Code/ember-cli-pemberly-lix_trunk/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/lib/worker.js:11:29)
```

This is likely due to the fact that Babel 7's options validate before running. The workers needed to be pooled based on Babel version.

**Comment by belgoros** [comment]
I have the same issue that appears totally in a random way when starting a server locally with `ember s`:
```
Build Error (broccoli-persistent-filter:Babel > [Babel: ember-basic-dropdown]) in ember-basic-dropdown/test-support/helpers.js

Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.


Stack Trace and Error Report: /var/folders/lv/b5jy1vv56lg19tcr5vd8rs880000gp/T/error.dump.e3699b14f4c3cf08c4fb35e745d6ea4f.log
```
Here is the content of the log file pointed to:
```
ERROR Summary:

  - broccoliBuilderErrorStack: ReferenceError: Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
    at throwUnknownError (/Users/Serguei/projects/decastore/decastore-front/node_modules/@babel/core/lib/config/validation/options.js:123:11)
    at Object.keys.forEach.key (/Users/Serguei/projects/decastore/decastore-front/node_modules/@babel/core/lib/config/validation/options.js:107:5)
    at Array.forEach (<anonymous>)
    at validateNested (/Users/Serguei/projects/decastore/decastore-front/node_modules/@babel/core/lib/config/validation/options.js:83:21)
    at validate (/Users/Serguei/projects/decastore/decastore-front/node_modules/@babel/core/lib/config/validation/options.js:74:10)
    at loadPrivatePartialConfig (/Users/Serguei/projects/decastore/decastore-front/node_modules/@babel/core/lib/config/partial.js:66:50)
    at loadFullConfig (/Users/Serguei/projects/decastore/decastore-front/node_modules/@babel/core/lib/config/full.js:43:39)
    at transformSync (/Users/Serguei/projects/decastore/decastore-front/node_modules/@babel/core/lib/transform.js:41:38)
    at Object.transform (/Users/Serguei/projects/decastore/decastore-front/node_modules/@babel/core/lib/transform.js:22:38)
    at resolve (/Users/Serguei/projects/decastore/decastore-front/node_modules/ember-intl/node_modules/broccoli-babel-transpiler/lib/worker.js:11:29)
  - codeFrame: Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
  - errorMessage: ember-basic-dropdown/test-support/helpers.js: Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
        in /var/folders/lv/b5jy1vv56lg19tcr5vd8rs880000gp/T/broccoli-8075ChJulvB68cd7/out-041-funnel_addon_tree_for_test_support_ember_basic_dropdown
        at broccoli-persistent-filter:Babel > [Babel: ember-basic-dropdown] (Babel: ember-basic-dropdown)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: ember-basic-dropdown/test-support/helpers.js
    - line: [undefined]
    - treeDir: /var/folders/lv/b5jy1vv56lg19tcr5vd8rs880000gp/T/broccoli-8075ChJulvB68cd7/out-041-funnel_addon_tree_for_test_support_ember_basic_dropdown
  - message: ember-basic-dropdown/test-support/helpers.js: Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
        in /var/folders/lv/b5jy1vv56lg19tcr5vd8rs880000gp/T/broccoli-8075ChJulvB68cd7/out-041-funnel_addon_tree_for_test_support_ember_basic_dropdown
        at broccoli-persistent-filter:Babel > [Babel: ember-basic-dropdown] (Babel: ember-basic-dropdown)
  - name: BuildError
  - nodeAnnotation: Babel: ember-basic-dropdown
  - nodeName: broccoli-persistent-filter:Babel > [Babel: ember-basic-dropdown]
  - originalErrorMessage: Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
  - stack: ReferenceError: Unknown option: .babel. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
    at throwUnknownError (/Users/Serguei/projects/decastore/decastore-front/node_modules/@babel/core/lib/config/validation/options.js:123:11)
    at Object.keys.forEach.key (/Users/Serguei/projects/decastore/decastore-front/node_modules/@babel/core/lib/config/validation/options.js:107:5)
    at Array.forEach (<anonymous>)
    at validateNested (/Users/Serguei/projects/decastore/decastore-front/node_modules/@babel/core/lib/config/validation/options.js:83:21)
    at validate (/Users/Serguei/projects/decastore/decastore-front/node_modules/@babel/core/lib/config/validation/options.js:74:10)
    at loadPrivatePartialConfig (/Users/Serguei/projects/decastore/decastore-front/node_modules/@babel/core/lib/config/partial.js:66:50)
    at loadFullConfig (/Users/Serguei/projects/decastore/decastore-front/node_modules/@babel/core/lib/config/full.js:43:39)
    at transformSync (/Users/Serguei/projects/decastore/decastore-front/node_modules/@babel/core/lib/transform.js:41:38)
    at Object.transform (/Users/Serguei/projects/decastore/decastore-front/node_modules/@babel/core/lib/transform.js:22:38)
    at resolve (/Users/Serguei/projects/decastore/decastore-front/node_modules/ember-intl/node_modules/broccoli-babel-transpiler/lib/worker.js:11:29)
```
AFter stopping and retsrting the errors goes away.
Using `Ember 3.7.2`. Any ideas ? Thank you.

**Comment by rwjblue** [comment]
https://github.com/babel/broccoli-babel-transpiler/pull/163 should address this
