### ISSUE TITLE
tests fail on recent versions of babel - 

### ISSUE THREAD

**Issue by jschilli** [babel/broccoli-babel-transpiler#16]
causing my PR to fail travis build - I'll look into what the issue is - placeholder for now
```
1) transpile ES6 to ES5 basic:
     TypeError: expected-inline-source-maps.js: Cannot read property 'sources' of null
      at File.mergeSourceMap (/Users/jschilling/dev/extern/active/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/file.js:475:10)
      at File.<anonymous> (/Users/jschilling/dev/extern/active/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/file.js:527:23)
      at File.generate (/Users/jschilling/dev/extern/active/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/file.js:493:24)
      at /Users/jschilling/dev/extern/active/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/file.js:401:20
      at module.exports (/Users/jschilling/dev/extern/active/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/helpers/parse.js:35:14)
      at File.<anonymous> (/Users/jschilling/dev/extern/active/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/file.js:399:12)
      at File.parse (/Users/jschilling/dev/extern/active/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/file.js:381:21)
      at Object.transform (/Users/jschilling/dev/extern/active/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/index.js:19:15)
      at Babel.transform (/Users/jschilling/dev/extern/active/broccoli-babel-transpiler/index.js:23:21)
      at Babel.processString (/Users/jschilling/dev/extern/active/broccoli-babel-transpiler/index.js:31:15)
      at Babel.Filter.processFile (/Users/jschilling/dev/extern/active/broccoli-babel-transpiler/node_modules/broccoli-filter/index.js:139:31)
      at /Users/jschilling/dev/extern/active/broccoli-babel-transpiler/node_modules/broccoli-filter/index.js:85:21
      at lib$rsvp$$internal$$tryCatch (/Users/jschilling/dev/extern/active/broccoli-babel-transpiler/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:489:16)
      at lib$rsvp$$internal$$invokeCallback (/Users/jschilling/dev/extern/active/broccoli-babel-transpiler/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:501:17)
      at /Users/jschilling/dev/extern/active/broccoli-babel-transpiler/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1095:13
      at lib$rsvp$asap$$flush (/Users/jschilling/dev/extern/active/broccoli-babel-transpiler/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1290:9)
      at process._tickCallback (node.js:355:11)
```

**Comment by jschilli** [comment]
this is a race condition, the inline source maps test is clobbering options before basic test runs

tracking now

**Comment by jschilli** [comment]
The basic test breaks when moving from babel-core 4.6.6 to 4.7.0

calling babel.transform without a `sourceMap` setting errors out - I haven't figured out the magic incantation yet to do so.

@sebmck^^

https://github.com/babel/babel/commit/f801772fc20f0a597f92c3af96080990e0b70011#diff-bd01d3140d65496689c40bb826e321edR479

**Comment by sebmck** [comment]
Please open an issue on the main Babel repo, thanks!

On Sunday, 29 March 2015, Jeff Schilling <notifications@github.com> wrote:

> The basic test breaks when moving from babel-core 4.6.6 to 4.7.0
>
> calling babel.transform without a sourceMap setting errors out - I
> haven't figured out the magic incantation yet to do so.
>
> @sebmck <https://github.com/sebmck>^^
>
> babel/babel@f801772#diff-bd01d3140d65496689c40bb826e321edR479
> <https://github.com/babel/babel/commit/f801772fc20f0a597f92c3af96080990e0b70011#diff-bd01d3140d65496689c40bb826e321edR479>
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/broccoli-babel-transpiler/issues/16#issuecomment-87249930>
> .
>


-- 
Sebastian McKenzie
