### ISSUE TITLE
Does not support latest broccoli-persistent-filter

### ISSUE THREAD

**Issue by lifeart** [babel/broccoli-babel-transpiler#216]
```stack
 - stack: TypeError: Class constructor Filter cannot be invoked without 'new'
    at new Babel (/Users/aleksandr_kanunnikov/Documents/repos/brn/frontend/node_modules/broccoli-babel-transpiler/index.js:58:10)
    at Class.transpileTree (/Users/aleksandr_kanunnikov/Documents/repos/brn/frontend/node_modules/ember-cli-babel/index.js:170:16)
    at Object.toTree (/Users/aleksandr_kanunnikov/Documents/repos/brn/frontend/node_modules/ember-cli-babel/index.js:180:30)
    at /Users/aleksandr_kanunnikov/Documents/repos/brn/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:188:26
    at Array.forEach (<anonymous>:null:null)
    at processPlugins (/Users/aleksandr_kanunnikov/Documents/repos/brn/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:186:11)
    at Function.module.exports.preprocessJs (/Users/aleksandr_kanunnikov/Documents/repos/brn/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:179:10)
    at Class.preprocessJs (/Users/aleksandr_kanunnikov/Documents/repos/brn/frontend/node_modules/ember-cli/lib/models/addon.js:1297:25)
    at Class.treeForAddonTestSupport (/Users/aleksandr_kanunnikov/Documents/repos/brn/frontend/node_modules/@ember/test-helpers/index.js:19:25)
    at Class._treeFor (/Users/aleksandr_kanunnikov/Documents/repos/brn/frontend/node_modules/ember-cli/lib/models/addon.js:668:33)
    at Class.treeFor (/Users/aleksandr_kanunnikov/Documents/repos/brn/frontend/node_modules/ember-cli/lib/models/addon.js:628:21)
    at /Users/aleksandr_kanunnikov/Documents/repos/brn/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:721:26
    at Array.reduce (<anonymous>:null:null)
```

```patch
diff --git a/node_modules/broccoli-babel-transpiler/index.js b/node_modules/broccoli-babel-transpiler/index.js
index f27d48e..f53cd01 100644
--- a/node_modules/broccoli-babel-transpiler/index.js
+++ b/node_modules/broccoli-babel-transpiler/index.js
@@ -1,3 +1,4 @@
+// @ts-check
 'use strict';
 
 const Filter     = require('broccoli-persistent-filter');
@@ -31,67 +32,123 @@ if(!heimdall.hasMonitor('babel')) {
   });
 }
 
-module.exports = Babel;
-function Babel(inputTree, _options) {
-  if (!(this instanceof Babel)) {
-    return new Babel(inputTree, _options);
-  }
+class Babel extends Filter {
+  constructor(inputTree, search, replace, _options = {}) {
+
+    let options = _options || {};
+    options.persist = 'persist' in options ? options.persist : true;
+    options.async = true;
 
-  let options = _options || {};
-  options.persist = 'persist' in options ? options.persist : true;
-  options.async = true;
+    if (options.browserPolyfill) {
+      let polyfillPath = require.resolve('@babel/polyfill/package.json');
+      polyfillPath = path.join(path.dirname(polyfillPath), "dist");
 
-  if (options.browserPolyfill) {
-    let polyfillPath = require.resolve('@babel/polyfill/package.json');
-    polyfillPath = path.join(path.dirname(polyfillPath), "dist");
+      let browserPolyfillPath = options.browserPolyfillPath || "browser-polyfill.js"
+      let polyfill = funnel(polyfillPath, {
+        files: ['polyfill.js'],
+        getDestinationPath: () => browserPolyfillPath
+      });
+      inputTree = mergeTrees([polyfill, inputTree]);
+    }
+    delete options.browserPolyfill;
+    delete options.browserPolyfillPath;
 
-    let browserPolyfillPath = options.browserPolyfillPath || "browser-polyfill.js"
-    let polyfill = funnel(polyfillPath, {
-      files: ['polyfill.js'],
-      getDestinationPath: () => browserPolyfillPath
+    super(inputTree, {
+      annotation: options.annotation
     });
-    inputTree = mergeTrees([polyfill, inputTree]);
-  }
-  delete options.browserPolyfill;
-  delete options.browserPolyfillPath;
 
-  Filter.call(this, inputTree, options);
+    delete options.persist;
+    delete options.async;
+    delete options.annotation;
+    delete options.description;
+  
+    this._optionsHash = null;
+    this.console = options.console || console;
+    this.throwUnlessParallelizable = options.throwUnlessParallelizable;
+  
+    delete options.console;
+    delete options.throwUnlessParallelizable;
+  
+    this.options = options;
+    this.extensions = this.options.filterExtensions || ['js'];
+    this.extensionsRegex = getExtensionsRegex(this.extensions);
+    this.name = 'broccoli-babel-transpiler';
+    this.targetExtension = 'js';
+  
+    if (this.options.helperWhiteList) {
+      this.helperWhiteList = this.options.helperWhiteList;
+    }
+  
+    // Note, Babel does not support this option so we must save it then
+    // delete it from the options hash
+    delete this.options.helperWhiteList;
   
-  delete options.persist;
-  delete options.async;
-  delete options.annotation;
-  delete options.description;
+    let { isParallelizable, errors } = transformIsParallelizable(options);
   
-  this._optionsHash = null;
-  this.console = options.console || console;
-  this.throwUnlessParallelizable = options.throwUnlessParallelizable;
+    heimdall.statsFor('babel').isParallelizable = isParallelizable;
   
-  delete options.console;
-  delete options.throwUnlessParallelizable;
+    if ((this.throwUnlessParallelizable || process.env.THROW_UNLESS_PARALLELIZABLE) && isParallelizable === false) {
+      throw new Error(this.toString() +
+        ' was configured to `throwUnlessParallelizable` and was unable to parallelize a plugin. \nplugins:\n' + joinCount(errors) + '\nPlease see: https://github.com/babel/broccoli-babel-transpiler#parallel-transpilation for more details');
+    }
 
-  this.options = options;
-  this.extensions = this.options.filterExtensions || ['js'];
-  this.extensionsRegex = getExtensionsRegex(this.extensions);
-  this.name = 'broccoli-babel-transpiler';
 
-  if (this.options.helperWhiteList) {
-    this.helperWhiteList = this.options.helperWhiteList;
   }
+  processString(string, relativePath){
+    heimdall.statsFor('babel').stringsProcessed++;
+
+    let options = this.copyOptions();
+  
+    options.filename = options.sourceFileName = relativePath;
   
-  // Note, Babel does not support this option so we must save it then
-  // delete it from the options hash
-  delete this.options.helperWhiteList;
+    if (options.moduleId === true) {
+      options.moduleId = replaceExtensions(this.extensionsRegex, options.filename);
+    }
   
-  let { isParallelizable, errors } = transformIsParallelizable(options);
+    let optionsObj = { 'babel' : options, 'cacheKey' : this._optionsHash};
+    return this.transform(string, optionsObj)
+      .then(transpiled => {
+        if (this.helperWhiteList) {
+          let invalidHelpers = transpiled.metadata.usedHelpers.filter(helper => {
+            return this.helperWhiteList.indexOf(helper) === -1;
+          });
   
-  heimdall.statsFor('babel').isParallelizable = isParallelizable;
+          validateHelpers(invalidHelpers, relativePath);
+        }
   
-  if ((this.throwUnlessParallelizable || process.env.THROW_UNLESS_PARALLELIZABLE) && isParallelizable === false) {
-    throw new Error(this.toString() +
-      ' was configured to `throwUnlessParallelizable` and was unable to parallelize a plugin. \nplugins:\n' + joinCount(errors) + '\nPlease see: https://github.com/babel/broccoli-babel-transpiler#parallel-transpilation for more details');
+        return transpiled.code;
+      });
+  }
+  transform(string, options) {
+    return transformString(string, options);
+  }
+  baseDir() {
+    return __dirname;
+  }
+  optionsHash() {
+    if (this._optionsHash == null) {
+      this._optionsHash =  optionsHash(this.options, this.console);
+    }
+  
+    return this._optionsHash;
+  }
+  cacheKeyProcessString(string, relativePath) {
+    return this.optionsHash() + Filter.prototype.cacheKeyProcessString.call(this, string, relativePath);
+  }
+  copyOptions() {
+    let cloned = clone(this.options);
+    if (cloned.filterExtensions) {
+      delete cloned.filterExtensions;
+    }
+    if (cloned.targetExtension) {
+      delete cloned.targetExtension;
+    }
+    return cloned;
   }
 }
 
+module.exports = Babel;
+
 function joinCount(list) {
   let summary = '';
 
@@ -102,17 +159,6 @@ function joinCount(list) {
   return summary;
 }
 
-Babel.prototype = Object.create(Filter.prototype);
-Babel.prototype.constructor = Babel;
-Babel.prototype.targetExtension = 'js';
-
-Babel.prototype.baseDir = function() {
-  return __dirname;
-};
-
-Babel.prototype.transform = function(string, options) {
-  return transformString(string, options);
-};
 
 /*
  * @private
@@ -120,54 +166,6 @@ Babel.prototype.transform = function(string, options) {
  * @method optionsString
  * @returns a stringified version of the input options
  */
-Babel.prototype.optionsHash = function() {
-  if (this._optionsHash == null) {
-    this._optionsHash =  optionsHash(this.options, this.console);
-  }
-
-  return this._optionsHash;
-};
-
-Babel.prototype.cacheKeyProcessString = function(string, relativePath) {
-  return this.optionsHash() + Filter.prototype.cacheKeyProcessString.call(this, string, relativePath);
-};
-
-Babel.prototype.processString = function(string, relativePath) {
-  heimdall.statsFor('babel').stringsProcessed++;
-
-  let options = this.copyOptions();
-
-  options.filename = options.sourceFileName = relativePath;
-
-  if (options.moduleId === true) {
-    options.moduleId = replaceExtensions(this.extensionsRegex, options.filename);
-  }
-
-  let optionsObj = { 'babel' : options, 'cacheKey' : this._optionsHash};
-  return this.transform(string, optionsObj)
-    .then(transpiled => {
-      if (this.helperWhiteList) {
-        let invalidHelpers = transpiled.metadata.usedHelpers.filter(helper => {
-          return this.helperWhiteList.indexOf(helper) === -1;
-        });
-
-        validateHelpers(invalidHelpers, relativePath);
-      }
-
-      return transpiled.code;
-    });
-};
-
-Babel.prototype.copyOptions = function() {
-  let cloned = clone(this.options);
-  if (cloned.filterExtensions) {
-    delete cloned.filterExtensions;
-  }
-  if (cloned.targetExtension) {
-    delete cloned.targetExtension;
-  }
-  return cloned;
-};
 
 function validateHelpers(invalidHelpers, relativePath) {
   if (invalidHelpers.length > 0) {
```

**Comment by csprocket777** [comment]
What ever happened with this? I'm experiencing this issue currently.

**Comment by roncodes** [comment]
Try this in your `package.json`

```json
"resolutions": {
   "broccoli-babel-transpiler/broccoli-persistent-filter": "^3.1.3"
}
  ```

**Comment by bertdeblock** [comment]
Seems this upgrade was done.
