### ISSUE TITLE
fails without options.filename

### ISSUE THREAD

**Issue by stefanpenner** [babel/broccoli-babel-transpiler#30]
```js
Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at replaceExtensions (/Users/stefanpenner/src/emberjs-build/node_modules/broccoli-babel-transpiler/index.js:15:16)
    at Babel.processString (/Users/stefanpenner/src/emberjs-build/node_modules/broccoli-babel-transpiler/index.js:46:24)
    at Babel.Filter.processFile (/Users/stefanpenner/src/emberjs-build/node_modules/broccoli-filter/index.js:136:31)
    at /Users/stefanpenner/src/emberjs-build/node_modules/broccoli-filter/index.js:85:21
    at lib$rsvp$$internal$$tryCatch (/Users/stefanpenner/src/emberjs-build/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/stefanpenner/src/emberjs-build/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:501:17)
    at /Users/stefanpenner/src/emberjs-build/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1095:13
    at lib$rsvp$asap$$flush (/Users/stefanpenner/src/emberjs-build/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1290:9)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

**Comment by stefanpenner** [comment]
writing a test...
