### ISSUE TITLE
update version + republish

### ISSUE THREAD

**Issue by nickdesaulniers** [babel/broccoli-babel-transpiler#40]
it looks like the [option was just added for browserPolyfill a few days ago](https://github.com/babel/broccoli-babel-transpiler/pull/24/files).  When I try to build I get the trace:

```
ReferenceError: [BABEL] csv_read.js: Unknown option: browserPolyfill
    at Logger.error (/Users/Nicholas/mozilla/caltrain/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/file/logger.js:45:11)
    at File.normaliseOptions (/Users/Nicholas/mozilla/caltrain/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/file/index.js:174:29)
    at new File (/Users/Nicholas/mozilla/caltrain/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/file/index.js:152:10)
    at Pipeline.transform (/Users/Nicholas/mozilla/caltrain/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/pipeline.js:127:16)
    at Babel.transform (/Users/Nicholas/mozilla/caltrain/node_modules/broccoli-babel-transpiler/index.js:60:21)
    at Babel.processString (/Users/Nicholas/mozilla/caltrain/node_modules/broccoli-babel-transpiler/index.js:72:25)
    at Babel.processFile (/Users/Nicholas/mozilla/caltrain/node_modules/broccoli-babel-transpiler/node_modules/cauliflower-filter/filter.js:166:31)
    at asyncProcessFile (/Users/Nicholas/mozilla/caltrain/node_modules/broccoli-babel-transpiler/node_modules/cauliflower-filter/filter.js:101:21)
    at lib$rsvp$$internal$$tryCatch (/Users/Nicholas/mozilla/caltrain/node_modules/broccoli-babel-transpiler/node_modules/cauliflower-filter/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/Nicholas/mozilla/caltrain/node_modules/broccoli-babel-transpiler/node_modules/cauliflower-filter/node_modules/rsvp/dist/rsvp.js:501:17)
    at /Users/Nicholas/mozilla/caltrain/node_modules/broccoli-babel-transpiler/node_modules/cauliflower-filter/node_modules/rsvp/dist/rsvp.js:1095:13
    at lib$rsvp$asap$$flush (/Users/Nicholas/mozilla/caltrain/node_modules/broccoli-babel-transpiler/node_modules/cauliflower-filter/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

Build failed
```

I have `"broccoli-babel-transpiler": "^5.2.3"` installed and my Brocfile.js looks like:

```js
module.exports = require('broccoli-babel-transpiler')('src', {
  browserPolyfill: true,
});
```

If I remove that option, everything builds just fine, but doesn't run in the browser (require is undefined).

**Comment by nickdesaulniers** [comment]
```
cat node_modules/broccoli-babel-transpiler/package.json | grep version
  "version": "5.2.3",
```
ah, I don't think the version number has been bumped, and the package has not yet been republished.

**Comment by nickdesaulniers** [comment]
If I change my package.json to be:

    "broccoli-babel-transpiler": "https://github.com/babel/broccoli-babel-transpiler.git"

The build now completes, but I still get the `require is not defined` error at runtime.

**Comment by fakalit** [comment]
Also experiencing the issue. with the same stacktrace and everything. should we default to manually adding to polyfill?

**Comment by givanse** [comment]
Version 5.3.0 was just published.

**Comment by stefanpenner** [comment]
Sorry I let this one slip
