### ISSUE TITLE
Plugin undefined didn't export default a Transformer instance

### ISSUE THREAD

**Issue by johnhamelink** [babel/broccoli-babel-transpiler#45]
Hey there,

After cloning a copy of an ember app I have, running `npm install` and `bower install` and then running `ember s`, I'm getting the following error:

```
[john:~/Public/customerQ/frontend] master(+1/-1)* ± ember s         
version: 1.13.0
Deprecation warning: sassOptions should be moved to your Brocfile
Livereload server on http://localhost:35729
Serving on http://localhost:4200/
File: frontend/adapters/application.js
Plugin undefined didn't export default a Transformer instance
TypeError: Plugin undefined didn't export default a Transformer instance
    at File.addPlugin (/home/john/Public/customerQ/frontend/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/file/index.js:283:13)
    at File.buildTransformers (/home/john/Public/customerQ/frontend/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/file/index.js:215:12)
    at new File (/home/john/Public/customerQ/frontend/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/file/index.js:89:10)
    at Object.transform (/home/john/Public/customerQ/frontend/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at Babel.transform (/home/john/Public/customerQ/frontend/node_modules/broccoli-babel-transpiler/index.js:24:21)
    at Babel.processString (/home/john/Public/customerQ/frontend/node_modules/broccoli-babel-transpiler/index.js:32:15)
    at Babel.Filter.processFile (/home/john/Public/customerQ/frontend/node_modules/broccoli-babel-transpiler/node_modules/broccoli-filter/index.js:139:31)
    at /home/john/Public/customerQ/frontend/node_modules/broccoli-babel-transpiler/node_modules/broccoli-filter/index.js:85:21
    at lib$rsvp$$internal$$tryCatch (/home/john/Public/customerQ/frontend/node_modules/broccoli-babel-transpiler/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/john/Public/customerQ/frontend/node_modules/broccoli-babel-transpiler/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:501:17
```

I've not been able to figure out where I've gone wrong - but this error seems to be coming from within broccoli-babel-transpiler. My package.json:

```
{
  "name": "frontend",
  "version": "0.0.0",
  "description": "Small description for frontend goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "1.13.0",
    "ember-cli-app-version": "0.4.0",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-chartist": "^0.2.9",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-divshot": "^0.1.7",
    "ember-cli-document-title": "0.1.0",
    "ember-cli-flash": "^1.3.2",
    "ember-cli-foundation-sass": "^1.1.1",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.1.1",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.15",
    "ember-cli-release": "0.2.3",
    "ember-cli-sass": "^4.0.1",
    "ember-cli-selectize": "^0.3.6",
    "ember-cli-simple-auth": "0.8.0",
    "ember-cli-simple-auth-devise": "0.8.0",
    "ember-cli-spinkit": "1.0.0",
    "ember-cli-uglify": "^1.0.1",
    "ember-cli-zero-clipboard": "1.0.2",
    "ember-data": "1.13.5",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.2",
    "ember-remarkable": "1.3.0",
    "ember-watson": "^0.5.9",
    "express": "^4.12.3",
    "glob": "^5.0.13",
    "initials-avatar": "0.0.8",
    "morgan": "^1.5.2",
    "ui-expanding-textarea": "0.0.12"
  }
}
```

**Comment by chadhietala** [comment]
Can you try `rm -rf node_modules && npm cache clean && npm install` from within the project?  Seems like you have a bad version of babel.

**Comment by johnhamelink** [comment]
That fixed it, thank you :smile:
